import { Montserrat } from '@next/font/google';
import "../styles/globals.css";

const montserrat = Montserrat({
  subsets: ['latin'],
  weights: [300, 400, 500, 700, 900],
});

export const metadata = {
  title: "Reto técnico - El Corte Inglés",
  description: "Generated by create next app, created by Alonso Caballero",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
